#!/usr/bin/env bash
# scripts/init.sh — Universal Setup Wizard
# Configures the boilerplate for your specific project

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
BOLD='\033[1m'; CYAN='\033[36m'; GREEN='\033[32m'; YELLOW='\033[33m'; RESET='\033[0m'

header() { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }
success() { echo -e "  ${GREEN}✓${RESET} $1"; }
prompt() { echo -e "  ${YELLOW}?${RESET} $1"; }

# ── Collect answers ───────────────────────────────────────────────────────────
header "🚀 Universal Boilerplate — Setup Wizard"
echo "   Answer a few questions to configure your project."

prompt "Project name (e.g. my-saas-app):"
read -r PROJECT_NAME
PROJECT_NAME="${PROJECT_NAME:-my-project}"

prompt "One-line description:"
read -r PROJECT_DESCRIPTION
PROJECT_DESCRIPTION="${PROJECT_DESCRIPTION:-A project built with the universal boilerplate}"

echo ""
prompt "Project type:"
echo "    1) saas          2) api          3) cli"
echo "    4) data-pipeline 5) ecommerce"
read -r TYPE_NUM
case "$TYPE_NUM" in
  2) PROJECT_TYPE="api" ;;
  3) PROJECT_TYPE="cli" ;;
  4) PROJECT_TYPE="data-pipeline" ;;
  5) PROJECT_TYPE="ecommerce" ;;
  *) PROJECT_TYPE="saas" ;;
esac

echo ""
prompt "Scale profile:"
echo "    1) solo       — single service, simple setup"
echo "    2) startup    — gateway + auth + core (default)"
echo "    3) enterprise — full microservices"
read -r PROFILE_NUM
case "$PROFILE_NUM" in
  1) PROJECT_PROFILE="solo" ;;
  3) PROJECT_PROFILE="enterprise" ;;
  *) PROJECT_PROFILE="startup" ;;
esac

echo ""
prompt "Primary language for core-service:"
echo "    1) typescript (default)  2) go  3) python  4) rust"
read -r LANG_NUM
case "$LANG_NUM" in
  2) PRIMARY_LANGUAGE="go" ;;
  3) PRIMARY_LANGUAGE="python" ;;
  4) PRIMARY_LANGUAGE="rust" ;;
  *) PRIMARY_LANGUAGE="typescript" ;;
esac

echo ""
prompt "Database engine:"
echo "    1) postgres (default)  2) mysql  3) mongodb  4) sqlite"
read -r DB_NUM
case "$DB_NUM" in
  2) DB_ENGINE="mysql";   DB_PROVIDER="mysql" ;;
  3) DB_ENGINE="mongodb"; DB_PROVIDER="mongodb" ;;
  4) DB_ENGINE="sqlite";  DB_PROVIDER="sqlite" ;;
  *) DB_ENGINE="postgres"; DB_PROVIDER="postgresql" ;;
esac

echo ""
prompt "Auth strategy:"
echo "    1) jwt (default)  2) oauth  3) api-key"
read -r AUTH_NUM
case "$AUTH_NUM" in
  2) AUTH_STRATEGY="oauth" ;;
  3) AUTH_STRATEGY="api-key" ;;
  *) AUTH_STRATEGY="jwt" ;;
esac

# ── Apply substitutions ───────────────────────────────────────────────────────
header "⚙️  Applying configuration..."

# Files to substitute
FILES=(
  ".claude/claude.md"
  ".claude/settings.json"
  ".claude/context/architecture.md"
  ".claude/context/auth-rules.md"
  ".claude/context/tech-stack.md"
  ".claude/context/db-schema.md"
  "orchestrator/configs/languages.yaml"
  "docs/prd.md"
  "docs/architecture.md"
  "README.md"
  "config/profiles/solo.yaml"
  "config/profiles/startup.yaml"
  "config/profiles/enterprise.yaml"
)

for file in "${FILES[@]}"; do
  if [ -f "$file" ]; then
    sed -i.bak \
      -e "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" \
      -e "s/{{PROJECT_DESCRIPTION}}/$PROJECT_DESCRIPTION/g" \
      -e "s/{{PROJECT_TYPE}}/$PROJECT_TYPE/g" \
      -e "s/{{PROJECT_PROFILE}}/$PROJECT_PROFILE/g" \
      -e "s/{{PRIMARY_LANGUAGE}}/$PRIMARY_LANGUAGE/g" \
      -e "s/{{DB_ENGINE}}/$DB_ENGINE/g" \
      -e "s/{{DB_PROVIDER}}/$DB_PROVIDER/g" \
      -e "s/{{AUTH_STRATEGY}}/$AUTH_STRATEGY/g" \
      "$file"
    rm -f "${file}.bak"
  fi
done
success "Template variables substituted"

# ── Write project config ──────────────────────────────────────────────────────
cat > config/project.yaml << EOF
# Generated by scripts/init.sh — edit manually if needed
project:
  name: $PROJECT_NAME
  description: "$PROJECT_DESCRIPTION"
  type: $PROJECT_TYPE
  profile: $PROJECT_PROFILE
  primaryLanguage: $PRIMARY_LANGUAGE
  dbEngine: $DB_ENGINE
  authStrategy: $AUTH_STRATEGY
  generatedAt: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
EOF
success "config/project.yaml written"

# ── Copy .env.example → .env ──────────────────────────────────────────────────
if [ ! -f .env ]; then
  cp .env.example .env
  # Patch .env with chosen values
  sed -i.bak \
    -e "s/^PROJECT_NAME=.*/PROJECT_NAME=$PROJECT_NAME/" \
    -e "s/^PROJECT_PROFILE=.*/PROJECT_PROFILE=$PROJECT_PROFILE/" \
    -e "s/^PRIMARY_LANGUAGE=.*/PRIMARY_LANGUAGE=$PRIMARY_LANGUAGE/" \
    -e "s/^DB_PROVIDER=.*/DB_PROVIDER=$DB_PROVIDER/" \
    -e "s/^AUTH_STRATEGY=.*/AUTH_STRATEGY=$AUTH_STRATEGY/" \
    .env
  rm -f .env.bak
  success ".env created from .env.example"
fi

# ── Profile: disable unused services ─────────────────────────────────────────
if [ "$PROJECT_PROFILE" = "solo" ]; then
  echo "" >> .env
  echo "# Solo profile: gateway and auth-service disabled" >> .env
fi

# ── Install dependencies ──────────────────────────────────────────────────────
header "📦 Installing dependencies..."
if command -v pnpm &>/dev/null; then
  pnpm install
  success "pnpm install complete"
elif command -v npm &>/dev/null; then
  npm install
  success "npm install complete"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
header "✅ Setup Complete!"
echo ""
echo -e "  Project:  ${BOLD}$PROJECT_NAME${RESET}"
echo -e "  Type:     $PROJECT_TYPE"
echo -e "  Profile:  $PROJECT_PROFILE"
echo -e "  Language: $PRIMARY_LANGUAGE"
echo -e "  DB:       $DB_ENGINE"
echo -e "  Auth:     $AUTH_STRATEGY"
echo ""
echo "  Next steps:"
echo "    1. Fill in secrets in .env"
echo "    2. make dev          — start all services"
echo "    3. make db-migrate   — run migrations"
echo ""
echo "  Read .claude/claude.md before your first AI-assisted task."

# ── Run initial context sync ──────────────────────────────────────────────────
header "🔄 Running initial context sync..."
echo "   This checks which .claude/context/ files need to be created."
echo "   You'll be prompted for any missing documents."
echo ""
bash scripts/sync-context.sh

# ── Run initial context sync ──────────────────────────────────────────────────
header "🔄 Running initial context sync..."
echo "   This checks which .claude/context/ files need to be created."
echo "   You will be prompted for any missing documents."
bash scripts/sync-context.sh
