#!/usr/bin/env bash
# =============================================================================
# scripts/sync-context.sh
# Syncs /docs/ → .claude/context/ using /templates/ as structure blueprints.
#
# BEHAVIOUR:
#   1. If .claude/context/<file> exists        → skip (use --force to overwrite)
#   2. If /docs/<file> exists                  → distill → write machine version
#   3. If neither exists                       → interactive brainstorm with user
#                                                 → write both /docs/ and .claude/context/
#
# USAGE:
#   bash scripts/sync-context.sh               # sync all, skip existing
#   bash scripts/sync-context.sh --force       # overwrite all context files
#   bash scripts/sync-context.sh --file prd    # sync single file
#   bash scripts/sync-context.sh --dry-run     # show what would happen
# =============================================================================

set -euo pipefail

# ── Terminal colours ──────────────────────────────────────────────────────────
BOLD='\033[1m'; CYAN='\033[36m'; GREEN='\033[32m'
YELLOW='\033[33m'; RED='\033[31m'; DIM='\033[2m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[sync]${RESET} $*"; }
success() { echo -e "${GREEN}[✓]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[!]${RESET} $*"; }
skip()    { echo -e "${DIM}[–]${RESET} $*"; }
ask()     { echo -e "${BOLD}${YELLOW}[?]${RESET} $1"; }
header()  { echo -e "\n${BOLD}${CYAN}$1${RESET}\n"; }

# ── Parse flags ───────────────────────────────────────────────────────────────
FORCE=false
DRY_RUN=false
TARGET_FILE=""

for arg in "$@"; do
  case "$arg" in
    --force)        FORCE=true ;;
    --dry-run)      DRY_RUN=true ;;
    --file=*)       TARGET_FILE="${arg#--file=}" ;;
  esac
done

# ── Load project config ───────────────────────────────────────────────────────
PROJECT_NAME="{{PROJECT_NAME}}"
PROJECT_TYPE="{{PROJECT_TYPE}}"
PROJECT_PROFILE="{{PROJECT_PROFILE}}"

if [ -f "config/project.yaml" ]; then
  PROJECT_NAME=$(grep "^  name:" config/project.yaml | awk '{print $2}' || echo "$PROJECT_NAME")
fi

# ── Manifest: template → docs source → context target ─────────────────────────
# Format: "template_stem|docs_filename|context_filename|friendly_name"
declare -a MANIFEST=(
  "prd|prd.md|prd.md|Product Requirements Document"
  "architecture|architecture.md|architecture.md|Architecture"
  "api-documentation|api-documentation.md|api-contracts.md|API Contracts"
  "api-rate-limit-policy|api-rate-limit-policy.md|api-rate-limits.md|API Rate Limit Policy"
  "db-schema|db-schema.md|db-schema.md|Database Schema"
  "adr|adr.md|adr.md|Architecture Decision Records"
  "security-model|security-model.md|security-model.md|Security Model"
  "data-flow|data-flow.md|data-flow.md|Data Flow"
  "runbook|runbook.md|runbook.md|Runbook"
  "test-plan|test-plan.md|test-plan.md|Test Plan"
  "onboarding|onboarding.md|onboarding.md|Developer Onboarding"
  "changelog|changelog.md|changelog.md|Changelog"
)

# ── Brainstorm question banks ─────────────────────────────────────────────────
brainstorm_prd() {
  local out_docs="$1" out_ctx="$2"
  header "📋 Let's build your PRD together"
  echo "  I'll ask you a few questions. Answer freely — even rough notes work."
  echo "  Press Enter to skip any question."
  echo ""

  ask "What problem does ${PROJECT_NAME} solve? (1-2 sentences)"
  read -r PROBLEM

  ask "Who are the primary users? (e.g. 'freelancers managing invoices')"
  read -r USERS

  ask "What is the single most important thing users can DO with this product?"
  read -r CORE_ACTION

  ask "List 3 must-have features for v1 (comma-separated):"
  read -r FEATURES
  IFS=',' read -ra FEAT_ARR <<< "$FEATURES"

  ask "What does SUCCESS look like? Give one measurable metric:"
  read -r SUCCESS_METRIC

  ask "What is explicitly OUT OF SCOPE for v1?"
  read -r OUT_OF_SCOPE

  ask "Any known risks or unknowns?"
  read -r RISKS

  # Write human /docs/ version
  cat > "$out_docs" << DOCEOF
# Product Requirements Document — ${PROJECT_NAME}

## Problem
${PROBLEM:-TBD}

## Users
${USERS:-TBD}

## Core Value Proposition
Users can: ${CORE_ACTION:-TBD}

## V1 Features
$(for f in "${FEAT_ARR[@]}"; do echo "- $(echo "$f" | xargs)"; done)

## Success Metric
${SUCCESS_METRIC:-TBD}

## Out of Scope (V1)
${OUT_OF_SCOPE:-TBD}

## Risks
${RISKS:-TBD}

---
_Generated by scripts/sync-context.sh on $(date -u +"%Y-%m-%d"). Refine this file freely._
DOCEOF

  # Write machine .claude/context/ version (dense)
  cat > "$out_ctx" << CTXEOF
# PRD: ${PROJECT_NAME}
_version: 0.1-draft | status: Draft | generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")_

## 1. PROBLEM STATEMENT
${PROBLEM:-FILL_IN}

## 2. GOALS
| # | Goal | Metric | Target |
|---|------|--------|--------|
| G1 | ${SUCCESS_METRIC:-FILL_IN} | TBD | TBD |

## 3. USERS
| Persona | JTBD |
|---------|------|
| ${USERS:-FILL_IN} | ${CORE_ACTION:-FILL_IN} |

## 4. REQUIREMENTS (MUST)
$(i=1; for f in "${FEAT_ARR[@]}"; do echo "| FR-00${i} | MUST | $(echo "$f" | xargs) | — |"; i=$((i+1)); done)

## 5. NON-GOALS (V1)
- ${OUT_OF_SCOPE:-FILL_IN}

## 6. RISKS
- ${RISKS:-FILL_IN}

## 7. NON-FUNCTIONAL REQUIREMENTS
| ID | Category | Requirement | Measure |
|----|----------|-------------|---------|
| NFR-001 | Performance | P99 < 500ms | Gateway under load |
| NFR-002 | Availability | 99.9% uptime | Monthly |

_Source: docs/prd.md | Sync: scripts/sync-context.sh_
CTXEOF
}

brainstorm_architecture() {
  local out_docs="$1" out_ctx="$2"
  header "🏛️  Let's map your architecture"

  ask "What services/components make up your system? (comma-separated, e.g. 'API, Auth, DB')"
  read -r SERVICES_RAW

  ask "What external systems does your product talk to? (e.g. 'Stripe, SendGrid, none')"
  read -r EXTERNAL

  ask "Where will this run? (e.g. 'AWS ECS', 'Fly.io', 'single VPS', 'k8s')"
  read -r HOSTING

  ask "What's the biggest architectural risk or unknown?"
  read -r ARCH_RISK

  IFS=',' read -ra SVC_ARR <<< "$SERVICES_RAW"

  cat > "$out_docs" << DOCEOF
# Architecture — ${PROJECT_NAME}

## Services
$(for s in "${SVC_ARR[@]}"; do echo "- $(echo "$s" | xargs)"; done)

## External Dependencies
${EXTERNAL:-None}

## Hosting
${HOSTING:-TBD}

## Key Risk
${ARCH_RISK:-TBD}

---
_Generated by scripts/sync-context.sh. Refine freely._
DOCEOF

  cat > "$out_ctx" << CTXEOF
# Architecture: ${PROJECT_NAME}
_version: 0.1-draft | generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")_

## SERVICES
| Service | Role |
|---------|------|
$(for s in "${SVC_ARR[@]}"; do echo "| $(echo "$s" | xargs) | TBD |"; done)

## EXTERNAL SYSTEMS
${EXTERNAL:-None}

## HOSTING / DEPLOYMENT
${HOSTING:-TBD}

## COMMUNICATION
All inter-service: JSON-RPC 2.0 / HTTP

## KEY RISKS
- ${ARCH_RISK:-TBD}

## PROFILE
Scale: ${PROJECT_PROFILE}
Primary language: ${PRIMARY_LANGUAGE:-typescript}

_Source: docs/architecture.md | Sync: scripts/sync-context.sh_
CTXEOF
}

brainstorm_generic() {
  local name="$1" out_docs="$2" out_ctx="$3" template="$4"
  header "📝 Let's create your ${name}"
  echo "  I don't have enough information yet to generate this automatically."
  echo ""
  warn "What to do:"
  echo "  1. Review the template:  cat templates/${template}.md"
  echo "  2. Create your version:  cp templates/${template}.md docs/${out_docs##*/}"
  echo "  3. Fill it in, then re-run: bash scripts/sync-context.sh"
  echo ""
  ask "Would you like me to copy the template as a starting point? (y/n)"
  read -r COPY_TEMPLATE
  if [[ "$COPY_TEMPLATE" =~ ^[Yy] ]]; then
    cp "templates/${template}.md" "$out_docs"
    success "Template copied to $out_docs — open it and fill in the placeholders."
    echo "  When done, run: bash scripts/sync-context.sh"
  fi
}

# ── Distill function: convert human /docs/ → machine .claude/context/ ────────
distill_to_context() {
  local docs_file="$1" ctx_file="$2" friendly_name="$3"

  info "Distilling ${docs_file} → ${ctx_file}..."

  # Read the docs file content
  local content
  content=$(cat "$docs_file")
  local word_count
  word_count=$(wc -w < "$docs_file")

  # Write machine-optimized version
  cat > "$ctx_file" << CTXEOF
# ${friendly_name}: ${PROJECT_NAME}
_distilled: $(date -u +"%Y-%m-%dT%H:%M:%SZ") | source: ${docs_file} | words: ${word_count}_
_machine-optimized: true | read-only: false (regenerated on sync)_

---

$(cat "$docs_file")

---
_Source: ${docs_file} | Regenerate: bash scripts/sync-context.sh_
CTXEOF

  success "Distilled → ${ctx_file}"
}

# ── Process each entry in manifest ────────────────────────────────────────────
SYNCED=0
SKIPPED=0
BRAINSTORMED=0
ERRORS=0

for entry in "${MANIFEST[@]}"; do
  IFS='|' read -r TMPL_STEM DOCS_FILE CTX_FILE FRIENDLY <<< "$entry"

  # Filter to single file if --file flag given
  if [ -n "$TARGET_FILE" ] && [ "$TARGET_FILE" != "$TMPL_STEM" ]; then
    continue
  fi

  DOCS_PATH="docs/${DOCS_FILE}"
  CTX_PATH=".claude/context/${CTX_FILE}"
  TMPL_PATH="templates/${TMPL_STEM}.md"

  echo ""
  info "Checking: ${FRIENDLY}"

  # ── Case 1: Context already exists ──────────────────────────────────────────
  if [ -f "$CTX_PATH" ] && [ "$FORCE" = false ]; then
    skip "Already exists: ${CTX_PATH}  (use --force to overwrite)"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  # ── Case 2: /docs/ version exists → distill ─────────────────────────────────
  if [ -f "$DOCS_PATH" ]; then
    if [ "$DRY_RUN" = true ]; then
      info "[dry-run] Would distill: ${DOCS_PATH} → ${CTX_PATH}"
    else
      distill_to_context "$DOCS_PATH" "$CTX_PATH" "$FRIENDLY"
    fi
    SYNCED=$((SYNCED + 1))
    continue
  fi

  # ── Case 3: Nothing exists → interactive brainstorm ─────────────────────────
  warn "Not found in /docs/: ${DOCS_FILE}"
  echo ""
  echo -e "  ${BOLD}${FRIENDLY}${RESET} is missing."
  echo "  Options:"
  echo "    1) Brainstorm with me now (quick Q&A)"
  echo "    2) Copy template to /docs/ and fill it yourself later"
  echo "    3) Skip for now"
  echo ""
  ask "Choose [1/2/3]:"
  read -r CHOICE

  case "$CHOICE" in
    1)
      if [ "$DRY_RUN" = true ]; then
        info "[dry-run] Would run brainstorm for: $FRIENDLY"
      else
        case "$TMPL_STEM" in
          prd)          brainstorm_prd "$DOCS_PATH" "$CTX_PATH" ;;
          architecture) brainstorm_architecture "$DOCS_PATH" "$CTX_PATH" ;;
          *)            brainstorm_generic "$FRIENDLY" "$DOCS_PATH" "$CTX_PATH" "$TMPL_STEM" ;;
        esac
      fi
      BRAINSTORMED=$((BRAINSTORMED + 1))
      ;;
    2)
      if [ -f "$TMPL_PATH" ]; then
        if [ "$DRY_RUN" = false ]; then
          cp "$TMPL_PATH" "$DOCS_PATH"
          success "Template copied → ${DOCS_PATH}. Fill it in, then re-run sync."
        else
          info "[dry-run] Would copy ${TMPL_PATH} → ${DOCS_PATH}"
        fi
      else
        warn "Template not found: ${TMPL_PATH}"
      fi
      SKIPPED=$((SKIPPED + 1))
      ;;
    *)
      skip "Skipped: $FRIENDLY"
      SKIPPED=$((SKIPPED + 1))
      ;;
  esac
done

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
header "Sync Complete"
echo -e "  ${GREEN}Synced:${RESET}       ${SYNCED}"
echo -e "  ${CYAN}Brainstormed:${RESET} ${BRAINSTORMED}"
echo -e "  ${DIM}Skipped:${RESET}      ${SKIPPED}"
if [ $ERRORS -gt 0 ]; then
  echo -e "  ${RED}Errors:${RESET}       ${ERRORS}"
fi
echo ""
echo "  Run again anytime: bash scripts/sync-context.sh"
echo "  Force overwrite:   bash scripts/sync-context.sh --force"
echo "  Single file:       bash scripts/sync-context.sh --file=prd"
echo "  Dry run:           bash scripts/sync-context.sh --dry-run"
